language: python
python:
  - "3.5"
  - "3.6"

cache: pip
# command to install dependencies
install:
  - pip install numpy
  - pip install -r requirements-dev.txt
  - pip install -e .
# command to run tests
script:
  - ipcluster start -n 2 --daemon
  #- travis_wait 20 make test
  - make test
